---
- hosts: master
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - etcd

- hosts: node
  become: yes
  become_method: sudo
  become_user: root
  environment:
    NODE_ADDRESS: "{{ ansible_ssh_host }}"
    MASTER_ADDRESS: 192.168.0.11
  roles:
    - docker

- hosts: master
  become: yes
  become_method: sudo
  become_user: root
  environment:
    MASTER_ADDRESS: 192.168.0.11
  roles:
    - kube-master

- hosts: node
  become: yes
  become_method: sudo
  become_user: root
  environment:
    NODE_ADDRESS: "{{ ansible_ssh_host }}"
    MASTER_ADDRESS: 192.168.0.11
  roles:
    - kube-node

- hosts: master
  become: yes
  become_method: sudo
  become_user: root
  environment:
    MASTER_ADDRESS: 192.168.0.11
  roles:
    - kube-dns