apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: counter-deployment
  labels:
    app: counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: huangydyn/counter-server:1
        env:
         - name: APP_ENV
           value: dev
        ports:
        - containerPort: 8080
